language: bash
dist: xenial
sudo: required
matrix:
  include:
  - env: TEMPLATE=gce-parity/16.04-ppc64le
    os: linux-ppc64le
  - env: TEMPLATE=ubuntu-systemd/16.04-ppc64le
    os: linux-ppc64le
  - env: TEMPLATE=gce-parity/18.04-ppc64le
    os: linux-ppc64le
  - env: TEMPLATE=ubuntu-systemd/18.04-ppc64le
    os: linux-ppc64le
  - env: TEMPLATE=ubuntu-systemd/18.04-s390x
    os: focal
    arch: s390x 
before_install:
      - lsb_release -a
      - uname -a
      - whoami
      - sudo apt-get install gpm libgpm-dev libcppunit-dev
script: chmod u+x ./bin/docker-build
