language: bash
dist: xenial
sudo: required
matrix:
  include:
  - env: TEMPLATE=gce-parity/16.04-ppc64le
    os: linux-ppc64le
  - env: TEMPLATE=ubuntu-systemd/16.04-ppc64le
    os: linux-ppc64le
  - env: TEMPLATE=gce-parity/18.04-ppc64le
    os: linux-ppc64le
  - env: TEMPLATE=ubuntu-systemd/18.04-ppc64le
    os: linux-ppc64le
  - env: TEMPLATE=ubuntu-systemd/18.04-arm64
    os: focal 
script: chmod u+x ./bin/docker-build
